/**
 * Example: REST API Tests — Users Endpoint
 * Auto-generated by AI QE Agent
 *
 * Run: npx playwright test --project=api tests/examples/api-users.api.spec.ts
 */
import { test, expect, request, APIRequestContext } from '@playwright/test';

const BASE_URL = process.env.API_BASE_URL || 'http://localhost:3000';

// ── Test Fixtures ────────────────────────────────────────────────────────────
const validUser = {
  name: 'Test User',
  email: `test-${Date.now()}@example.com`,
  password: 'SecurePass123!',
};

test.describe('Users API', () => {
  let apiContext: APIRequestContext;
  let authToken: string;
  let createdUserId: string;

  test.beforeAll(async () => {
    apiContext = await request.newContext({ baseURL: BASE_URL });

    // Authenticate
    const loginResponse = await apiContext.post('/auth/login', {
      data: { email: 'admin@example.com', password: 'adminpass' },
    });

    if (loginResponse.ok()) {
      const body = await loginResponse.json();
      authToken = body.token || body.access_token || '';
    }
  });

  test.afterAll(async () => {
    await apiContext.dispose();
  });

  // ── POST /users ────────────────────────────────────────────────────────────
  test.describe('POST /users — Create User', () => {
    test('should create a user with valid data', async () => {
      const response = await apiContext.post('/users', {
        data: validUser,
        headers: { Authorization: `Bearer ${authToken}` },
      });

      expect(response.status()).toBe(201);
      const body = await response.json();
      expect(body).toHaveProperty('id');
      expect(body.email).toBe(validUser.email);
      expect(body).not.toHaveProperty('password'); // Never expose password
      createdUserId = body.id;
    });

    test('should return 400 for missing required fields', async () => {
      const response = await apiContext.post('/users', {
        data: { name: 'Incomplete User' }, // Missing email and password
        headers: { Authorization: `Bearer ${authToken}` },
      });

      expect([400, 422]).toContain(response.status());
      const body = await response.json();
      expect(body).toHaveProperty('error');
    });

    test('should return 409 for duplicate email', async () => {
      const response = await apiContext.post('/users', {
        data: validUser, // Same email as created above
        headers: { Authorization: `Bearer ${authToken}` },
      });

      expect(response.status()).toBe(409);
    });

    test('should return 401 without authentication', async () => {
      const response = await apiContext.post('/users', {
        data: validUser,
      });

      expect(response.status()).toBe(401);
    });
  });

  // ── GET /users ─────────────────────────────────────────────────────────────
  test.describe('GET /users — List Users', () => {
    test('should return a paginated list of users', async () => {
      const response = await apiContext.get('/users', {
        headers: { Authorization: `Bearer ${authToken}` },
        params: { page: '1', limit: '10' },
      });

      expect(response.status()).toBe(200);
      const body = await response.json();
      expect(Array.isArray(body.data || body)).toBeTruthy();
    });

    test('should filter users by email', async () => {
      const response = await apiContext.get('/users', {
        headers: { Authorization: `Bearer ${authToken}` },
        params: { email: validUser.email },
      });

      expect(response.status()).toBe(200);
      const body = await response.json();
      const users = body.data || body;
      if (Array.isArray(users) && users.length > 0) {
        expect(users[0].email).toBe(validUser.email);
      }
    });
  });

  // ── GET /users/:id ─────────────────────────────────────────────────────────
  test.describe('GET /users/:id — Get User by ID', () => {
    test('should return a specific user', async () => {
      test.skip(!createdUserId, 'No user ID available');

      const response = await apiContext.get(`/users/${createdUserId}`, {
        headers: { Authorization: `Bearer ${authToken}` },
      });

      expect(response.status()).toBe(200);
      const body = await response.json();
      expect(body.id).toBe(createdUserId);
    });

    test('should return 404 for non-existent user', async () => {
      const response = await apiContext.get('/users/non-existent-id-12345', {
        headers: { Authorization: `Bearer ${authToken}` },
      });

      expect(response.status()).toBe(404);
    });
  });

  // ── PUT /users/:id ─────────────────────────────────────────────────────────
  test.describe('PUT /users/:id — Update User', () => {
    test('should update user name', async () => {
      test.skip(!createdUserId, 'No user ID available');

      const response = await apiContext.put(`/users/${createdUserId}`, {
        data: { name: 'Updated Name' },
        headers: { Authorization: `Bearer ${authToken}` },
      });

      expect([200, 204]).toContain(response.status());
    });
  });

  // ── DELETE /users/:id ──────────────────────────────────────────────────────
  test.describe('DELETE /users/:id — Delete User', () => {
    test('should delete a user', async () => {
      test.skip(!createdUserId, 'No user ID available');

      const response = await apiContext.delete(`/users/${createdUserId}`, {
        headers: { Authorization: `Bearer ${authToken}` },
      });

      expect([200, 204]).toContain(response.status());
    });

    test('should return 404 when deleting already deleted user', async () => {
      test.skip(!createdUserId, 'No user ID available');

      const response = await apiContext.delete(`/users/${createdUserId}`, {
        headers: { Authorization: `Bearer ${authToken}` },
      });

      expect(response.status()).toBe(404);
    });
  });

  // ── Parametrized validation tests ─────────────────────────────────────────
  const invalidEmails = [
    ['empty string', ''],
    ['missing @', 'notanemail'],
    ['missing domain', 'user@'],
    ['spaces', 'user @example.com'],
  ];

  for (const [description, email] of invalidEmails) {
    test(`should reject invalid email — ${description}`, async () => {
      const response = await apiContext.post('/users', {
        data: { ...validUser, email },
        headers: { Authorization: `Bearer ${authToken}` },
      });

      expect([400, 422]).toContain(response.status());
    });
  }
});
