/**
 * Example: Login Page E2E Tests
 * Auto-generated by AI QE Agent — then human-reviewed.
 *
 * Run: npx playwright test tests/examples/login.spec.ts
 */
import { test, expect, Page } from '@playwright/test';

// ── Page Object Model ────────────────────────────────────────────────────────
class LoginPage {
  constructor(private page: Page) {}

  async goto() {
    await this.page.goto('/login');
    await expect(this.page).toHaveTitle(/login/i);
  }

  async fillEmail(email: string) {
    await this.page.getByLabel(/email/i).fill(email);
  }

  async fillPassword(password: string) {
    await this.page.getByLabel(/password/i).fill(password);
  }

  async submit() {
    await this.page.getByRole('button', { name: /sign in|log in/i }).click();
  }

  async login(email: string, password: string) {
    await this.fillEmail(email);
    await this.fillPassword(password);
    await this.submit();
  }

  async getErrorMessage() {
    return this.page.getByRole('alert').textContent();
  }
}

// ── Tests ────────────────────────────────────────────────────────────────────
test.describe('Login Page', () => {
  let loginPage: LoginPage;

  test.beforeEach(async ({ page }) => {
    loginPage = new LoginPage(page);
    await loginPage.goto();
  });

  test('should display the login form correctly', async ({ page }) => {
    await expect(page.getByLabel(/email/i)).toBeVisible();
    await expect(page.getByLabel(/password/i)).toBeVisible();
    await expect(page.getByRole('button', { name: /sign in|log in/i })).toBeEnabled();
  });

  test('should login successfully with valid credentials', async ({ page }) => {
    await loginPage.login(
      process.env.TEST_USER_EMAIL || 'user@example.com',
      process.env.TEST_USER_PASSWORD || 'password123'
    );

    // Should redirect to dashboard
    await expect(page).toHaveURL(/dashboard|home/i);
    await expect(page.getByRole('heading', { name: /welcome|dashboard/i })).toBeVisible();
  });

  test('should show error when submitting empty form', async ({ page }) => {
    await loginPage.submit();

    // HTML5 validation or error message
    const emailInput = page.getByLabel(/email/i);
    await expect(emailInput).toBeFocused();
  });

  test('should show error for invalid credentials', async ({ page }) => {
    await loginPage.login('wrong@example.com', 'wrongpassword');

    const error = await loginPage.getErrorMessage();
    expect(error).toMatch(/invalid|incorrect|wrong|failed/i);
  });

  test('should show validation error for invalid email format', async ({ page }) => {
    await loginPage.fillEmail('not-an-email');
    await loginPage.fillPassword('password123');
    await loginPage.submit();

    const emailInput = page.getByLabel(/email/i);
    const validationMessage = await emailInput.evaluate(
      (el: HTMLInputElement) => el.validationMessage
    );
    expect(validationMessage).toBeTruthy();
  });

  test('should toggle password visibility when clicking show/hide button', async ({ page }) => {
    const passwordInput = page.getByLabel(/password/i);
    const toggleBtn = page.getByRole('button', { name: /show|hide password/i });

    await passwordInput.fill('mypassword');
    await expect(passwordInput).toHaveAttribute('type', 'password');

    if (await toggleBtn.isVisible()) {
      await toggleBtn.click();
      await expect(passwordInput).toHaveAttribute('type', 'text');
    } else {
      test.skip();
    }
  });

  test('should navigate to forgot password page', async ({ page }) => {
    await page.getByRole('link', { name: /forgot password/i }).click();
    await expect(page).toHaveURL(/forgot|reset/i);
  });

  test('should be keyboard navigable', async ({ page }) => {
    await page.keyboard.press('Tab'); // Focus email
    await page.keyboard.type('user@example.com');
    await page.keyboard.press('Tab'); // Focus password
    await page.keyboard.type('password123');
    await page.keyboard.press('Tab'); // Focus submit
    await page.keyboard.press('Enter');

    // Should attempt login
    await page.waitForLoadState('domcontentloaded');
  });
});
