/**
 * Example: Mobile & Responsive Design Tests
 * Auto-generated by AI QE Agent
 *
 * Run: npx playwright test --project=mobile-chrome tests/examples/mobile-responsive.spec.ts
 */
import { test, expect, devices } from '@playwright/test';

const TARGET_URL = process.env.BASE_URL || 'http://localhost:3000';

// Move test.use to top level (Playwright requirement for device emulation)
test.use({ ...devices['Pixel 5'] });

test.describe('Mobile Responsiveness', () => {

  test('should display mobile navigation (hamburger menu)', async ({ page }) => {
    await page.goto(TARGET_URL);

    const hamburger = page.getByRole('button', { name: /menu|hamburger|nav toggle/i })
      .or(page.locator('[aria-label="menu"]'))
      .or(page.locator('.hamburger, .menu-toggle, .navbar-toggler'));

    await expect(hamburger).toBeVisible();
    await hamburger.click();

    const nav = page.getByRole('navigation');
    await expect(nav).toBeVisible();
  });

  test('should not have horizontal scrollbar on mobile', async ({ page }) => {
    await page.goto(TARGET_URL);

    const hasHorizontalScroll = await page.evaluate(() => {
      return document.documentElement.scrollWidth > window.innerWidth;
    });

    expect(hasHorizontalScroll).toBe(false);
  });

  test('should have tap targets larger than 44px', async ({ page }) => {
    await page.goto(TARGET_URL);

    const smallTargets = await page.evaluate(() => {
      const interactive = Array.from(
        document.querySelectorAll('button, a, input, select, textarea, [role="button"]')
      );
      return interactive
        .filter((el) => {
          const rect = el.getBoundingClientRect();
          return (rect.width > 0 && rect.width < 44) || (rect.height > 0 && rect.height < 44);
        })
        .map((el) => ({
          tag: el.tagName,
          text: el.textContent?.trim().substring(0, 30),
          width: el.getBoundingClientRect().width,
          height: el.getBoundingClientRect().height,
        }));
    });

    // Log but don't fail — informational
    if (smallTargets.length > 0) {
      console.warn(`⚠️  ${smallTargets.length} small tap targets found:`, smallTargets);
    }
  });

  test('should load within acceptable time on mobile', async ({ page }) => {
    const start = Date.now();
    await page.goto(TARGET_URL, { waitUntil: 'load' });
    const loadTime = Date.now() - start;

    // Allow 5s on mobile (slower network simulation)
    expect(loadTime).toBeLessThan(5000);
  });
});

test.describe('Cross-Device Layout', () => {
  const viewports = [
    { name: 'Mobile S (320px)', width: 320, height: 568 },
    { name: 'Mobile M (375px)', width: 375, height: 667 },
    { name: 'Mobile L (425px)', width: 425, height: 896 },
    { name: 'Tablet (768px)', width: 768, height: 1024 },
    { name: 'Desktop (1280px)', width: 1280, height: 800 },
  ];

  for (const viewport of viewports) {
    test(`should render correctly at ${viewport.name}`, async ({ page }) => {
      await page.setViewportSize({ width: viewport.width, height: viewport.height });
      await page.goto(TARGET_URL);
      await page.waitForLoadState('networkidle');

      // Page should not have JS errors
      const errors: string[] = [];
      page.on('pageerror', (err) => errors.push(err.message));

      // Core content should be visible
      const mainContent = page.locator('main, [role="main"], #content, #app, body');
      await expect(mainContent.first()).toBeVisible();

      expect(errors).toHaveLength(0);
    });
  }
});
